version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: rentals_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - mysql
    networks:
      - rentals

  nginx:
    image: nginx:latest
    container_name: rentals_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - rentals

  mysql:
    image: mysql:8.0
    container_name: rentals_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rentals
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rentals

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rentals_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - rentals
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"  
      - "1025:1025" 
    networks:
      - rentals


volumes:
  db_data:

networks:
  rentals:
    driver: bridge




